### ISSUE TITLE
Song duration is 0

### ISSUE THREAD

**Issue by AlexInCube** [LakhindarPal/distube-apple-music#1]
I am try to play this song and 'duration' and 'formattedDuration' is zero.
https://music.apple.com/us/album/the-rebel-path/1544457960?i=1544457964

**Comment by LakhindarPal** [comment]
Duration is not available because it is not the streamed song, `song.stream.song` is available only when the song plays to reduce unnecessary requests and response time.

This is the nature of infoExtractor.

**Comment by AlexInCube** [comment]
But Spotify plugin for Distube is InfoExtractor, and spotify plugin provide duration for songs. So this is not "nature of infoExtractor"

**Comment by LakhindarPal** [comment]
You're right, I'll fix this in next release
